services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: starwars-backend
    ports:
      - "8000:8000"
    environment:
      - SWAPI_BASE_URL=${SWAPI_BASE_URL:-https://swapi.info/api}
      - CACHE_TTL=${CACHE_TTL:-3600}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CORS_ORIGINS=${CORS_ORIGINS:-["http://localhost:6969"]}
    volumes:
      - ./backend:/code
    networks:
      - starwars-network

networks:
  starwars-network:
    driver: bridge
